"use client";

import React, { useState } from 'react';
import { analyzeMatch } from '@/app/actions/analysis';
import { useAuth } from '@/app/Providers/AuthProvider';

type MatchAnalysisPanelProps = {
    matchId: string;
    initialAnalysis: string | null;
    summonerName: string;
    championName: string;
    kda: string;
    win: boolean;
};

export default function MatchAnalysisPanel({
    matchId,
    initialAnalysis,
    summonerName,
    championName,
    kda,
    win
}: MatchAnalysisPanelProps) {
    const [analysis, setAnalysis] = useState<string | null>(initialAnalysis);
    const [isAnalyzing, setIsAnalyzing] = useState(false);
    const [apiKey, setApiKey] = useState("");
    const [showKeyInput, setShowKeyInput] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const { user } = useAuth(); // Assume user loaded by page

    const handleAnalyze = async () => {
        setIsAnalyzing(true);
        setError(null);
        
        // Try getting key from local storage if not provided
        const keyToUse = apiKey || localStorage.getItem("gemini_api_key") || undefined;

        try {
            const res = await analyzeMatch(matchId, summonerName, championName, kda, win, keyToUse);
            
            if (res.success && res.advice) {
                setAnalysis(res.advice);
                if (apiKey) {
                     localStorage.setItem("gemini_api_key", apiKey); // Persist if success
                }
            } else {
                if (res.error?.includes("API Key")) {
                    setShowKeyInput(true);
                    setError("API Key is required/invalid. Please enter your Gemini API Key.");
                } else {
                    setError(res.error || "Analysis failed.");
                }
            }
        } catch (e: any) {
            setError(e.message || "Unknown error occurred.");
        } finally {
            setIsAnalyzing(false);
        }
    };

    return (
        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-xl mt-6">
            <div className="bg-slate-800/80 p-4 border-b border-slate-700 flex justify-between items-center">
                <h3 className="font-bold text-white flex items-center gap-2">
                    <span className="text-xl">🤖</span> AI MATCH DIAGNOSIS
                </h3>
            </div>

            <div className="p-6">
                {error && (
                    <div className="bg-red-500/20 text-red-300 p-3 rounded mb-4 text-sm whitespace-pre-wrap">
                        {error}
                    </div>
                )}

                {analysis ? (
                    <div className="animate-fadeIn">
                        {analysis.split("\n").map((line, index) => (
                            <p
                                key={index}
                                className={`mb-3 tracking-wide leading-relaxed ${
                                    line.trim().startsWith("1.") ||
                                    line.trim().startsWith("2.") ||
                                    line.trim().startsWith("3.") ||
                                    line.includes("良かった点") ||
                                    line.includes("改善点") ||
                                    line.includes("次へのアクション")
                                        ? "font-bold text-yellow-200 mt-4 text-base border-l-4 border-yellow-500 pl-3 bg-yellow-500/5 py-1"
                                        : "text-slate-300 text-sm"
                                }`}
                            >
                                {line}
                            </p>
                        ))}
                         <div className="mt-6 text-right text-xs text-slate-500 font-mono">
                            Analysis generated by Gemini 1.5 Flash
                        </div>
                    </div>
                ) : (
                    <div className="text-center py-10">
                        <div className="mb-6">
                            <h4 className="text-slate-300 font-bold mb-2">Detailed Match Analysis Not Found</h4>
                            <p className="text-slate-500 text-sm max-w-md mx-auto">
                                Get a complete breakdown of your performance, turning points, and specific advice to improve your win rate.
                            </p>
                        </div>

                        {showKeyInput && (
                             <div className="max-w-sm mx-auto mb-4 animate-fadeIn">
                                <label className="block text-left text-xs text-slate-400 mb-1">Your Gemini API Key (Free)</label>
                                <input 
                                    type="password"
                                    value={apiKey}
                                    onChange={(e) => setApiKey(e.target.value)}
                                    placeholder="AIzaSy..."
                                    className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-white focus:border-blue-500 outline-none"
                                />
                                <p className="text-[10px] text-slate-500 text-left mt-1">
                                    <a href="https://aistudio.google.com/app/apikey" target="_blank" className="underline hover:text-blue-400">Get a free key here</a>. Key is stored locally.
                                </p>
                             </div>
                        )}

                        <button 
                            onClick={handleAnalyze}
                            disabled={isAnalyzing}
                            className="bg-gradient-to-r from-blue-600 to-cyan-500 text-white font-bold px-8 py-3 rounded-full shadow-lg hover:shadow-cyan-500/25 hover:scale-105 transition-all text-sm disabled:opacity-50 disabled:scale-100 border border-white/10"
                        >
                            {isAnalyzing ? "ANALYZING REPLAY..." : "✨ START START ANALYSIS"}
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
}
